/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admingui;

import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import java.sql.Connection;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author MSI_GS
 */
public class accessAdmin extends javax.swing.JPanel {
 private Image backgroundImage;

    private static final String url =
            "jdbc:sqlite:" + System.getProperty("user.dir") + "/parc.db";

    Connection con;
   
     
    /**
     * Creates new form accessAdmin
     */
    public accessAdmin() {
        
        initComponents();
        try {

            con = DriverManager.getConnection(url);

        } catch (SQLException e) {

            e.printStackTrace();
        }
        getSS();
       
        
    }
@Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        g.drawImage(backgroundImage, 0, 0, this);
    }
    
 public void setPanelBackgroundImage(Image image) {
    ImageIcon icon = new ImageIcon(image);
    JLabel label = new JLabel(icon);
    ShowPanel.removeAll();
    ShowPanel.add(label);
    ShowPanel.revalidate();
    ShowPanel.repaint();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        AboutBtn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ss = new javax.swing.JLabel();
        ShowPanel = new javax.swing.JPanel();
        EmployeBtn = new javax.swing.JButton();
        GamesBtn = new javax.swing.JButton();
        FinanceBtn = new javax.swing.JButton();
        GrievanceBtn = new javax.swing.JButton();

        MenuPanel.setBackground(new java.awt.Color(26, 55, 77));

        jButton2.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(accessAdmin.class.getResource("/admingui/icons/ferris-wheels.png"))); // NOI18N
        jButton2.setText(" Operations");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(accessAdmin.class.getResource("/admingui/icons/icons8-logout-32 (1).png"))); // NOI18N
        jButton1.setText("Logout    ");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(accessAdmin.class.getResource("/images/amusement-park (1).png"))); // NOI18N

        jButton5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(accessAdmin.class.getResource("/admingui/icons/calendar.png"))); // NOI18N
        jButton5.setText("  Calendar   ");
        jButton5.setToolTipText("");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        AboutBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        AboutBtn.setIcon(new javax.swing.ImageIcon(accessAdmin.class.getResource("/admingui/icons/info.png"))); // NOI18N
        AboutBtn.setText(" About      ");
        AboutBtn.setActionCommand(" About         ");
        AboutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutBtnActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(accessAdmin.class.getResource("/admingui/icons/user (1).png"))); // NOI18N
        jButton6.setText(" Account     ");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AboutBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(AboutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(45, 45, 45))
        );

        jPanel4.setBackground(new java.awt.Color(26, 55, 77));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin");

        jLabel3.setIcon(new javax.swing.ImageIcon(accessAdmin.class.getResource("/images/profile (1).png"))); // NOI18N

        ss.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        ss.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );

        ShowPanel.setPreferredSize(new java.awt.Dimension(1635, 808));

        EmployeBtn.setForeground(new java.awt.Color(255, 255, 255));
        EmployeBtn.setIcon(new javax.swing.ImageIcon(accessAdmin.class.getResource("/images/mml.png"))); // NOI18N
        EmployeBtn.setText("EmployeBtn");
        EmployeBtn.setToolTipText("");
        EmployeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmployeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeBtnActionPerformed(evt);
            }
        });

        GamesBtn.setForeground(new java.awt.Color(0, 153, 153));
        GamesBtn.setIcon(new javax.swing.ImageIcon(accessAdmin.class.getResource("/images/gdf.png"))); // NOI18N
        GamesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GamesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GamesBtnActionPerformed(evt);
            }
        });

        FinanceBtn.setIcon(new javax.swing.ImageIcon(accessAdmin.class.getResource("/images/eeee.png"))); // NOI18N
        FinanceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FinanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinanceBtnActionPerformed(evt);
            }
        });

        GrievanceBtn.setIcon(new javax.swing.ImageIcon(accessAdmin.class.getResource("/images/ranim_1.png"))); // NOI18N
        GrievanceBtn.setText("jButton10");
        GrievanceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GrievanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrievanceBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ShowPanelLayout = new javax.swing.GroupLayout(ShowPanel);
        ShowPanel.setLayout(ShowPanelLayout);
        ShowPanelLayout.setHorizontalGroup(
            ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowPanelLayout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addGroup(ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EmployeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FinanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GamesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GrievanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(494, Short.MAX_VALUE))
        );
        ShowPanelLayout.setVerticalGroup(
            ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GamesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FinanceBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GrievanceBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1428, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ShowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE))
                    .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 adminOperationPanel v=new adminOperationPanel();
        showForm(v);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
    currentFrame.dispose();
JFrame frame = new JFrame("Digi-Parc");
frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
 frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
 frame.setVisible(true);
JPanel panel_1 = new Login.ImagePanel(accessAdmin.class.getResource("/admingui/icons/walid1.jpg"));
                   panel_1.setLayout(null);
	  	 	  	
        frame.getContentPane().add(panel_1);
        
       
        
	    
	    
	    JPanel lblda = new Login.ImagePanel(accessAdmin.class.getResource("/admingui/icons/b.jpg"));
            lblda.setLayout(null);
	    lblda.setBounds(340,120,835,600);
	    
	    panel_1.add(lblda);
	  
	
//	  JPanel st=new ImagePanel("C:\\Users\\MSI_GS\\Downloads\\walid.jpg");
//	  st.setLayout(null);
//	  st.setBounds(340,120,250,600);
//	  
//	  panel_1.add(st);
//	

	 
	  JLabel lblNewLabel = new JLabel("LOGIN");
	    lblNewLabel.setForeground(Color.white);
	    lblNewLabel.setFont(new Font("Bookman Old Style", Font.BOLD, 50));
	    lblNewLabel.setBounds(335, 100, 200, 50);
	 
     
	   lblda.add(lblNewLabel);
	  
	  
	  
  
	  
	    
	    RoundJTextField textField_1  = new RoundJTextField(15, accessAdmin.class.getResource("/admingui/icons/user.png").getPath());
	    textField_1.setBounds(285, 200, 250, 28);
	    textField_1.setForeground(Color.black);
	    textField_1.setPlaceholder(" Username");
	    lblda.add(textField_1);
	    
	      
	      
	      RoundJTextFieldd passwordField_1  = new RoundJTextFieldd(15, accessAdmin.class.getResource("/images/password.png").getPath());
	     passwordField_1.setBounds(284, 265, 250, 28);
	    passwordField_1.setPlaceholder(" Password");
	    lblda.add(passwordField_1);
	    
	   
	      
	 

	    MyButton btnLogin = new MyButton();
	    btnLogin.setText("Login");
        btnLogin.setRadius(23);
        btnLogin.setBorderPainted(false);
	    btnLogin.setBackground(Color.white);
	    btnLogin.setForeground(Color.black);
	    
	   btnLogin.setBounds(310, 360, 200, 30); 
	    btnLogin.setFocusPainted(false);
	    lblda.add(btnLogin);

	    

	    JCheckBox showpass = new JCheckBox("Show password");
	      
	      
	      showpass.setFont(new Font("Sitka Small", Font.PLAIN, 13));
	      
	      showpass.setOpaque(false);
	      showpass.setBorderPainted(false);
	      showpass.setFocusPainted(false);
              showpass.setForeground(Color.white);
	      showpass.setBounds(350, 320, 120, 21);
	      lblda.add(showpass);

frame.getContentPane().add(panel_1);

frame.pack();
frame.setLocationRelativeTo(null);
frame.setVisible(true);
showpass.addActionListener(new ActionListener() {
	          public void actionPerformed(ActionEvent e) {
	              if(showpass.isSelected()) {
	               (passwordField_1).setEchoChar((char)0);
	              } else {
	               passwordField_1.setEchoChar('•');
	              }
	          }
	      });
	       btnLogin.addActionListener(new ActionListener() {
    public void actionPerformed(ActionEvent e) {
        String username = textField_1.getText();
        String password = new String(passwordField_1.getText());
        
        
        if (AuthenticationHandler.authenticateAdmin(username, password)==true) {
                    accessAdmin adminPanel = new accessAdmin();
                    passwordField_1.setText(null);
                    textField_1.setText(null);
            FlatAnimatedLafChange.showSnapshot();

                frame.getContentPane().remove(panel_1);
                frame.getContentPane().add(adminPanel);
            

            
            frame.revalidate();
            frame.repaint();
            FlatAnimatedLafChange.hideSnapshotWithAnimation();  
        } 
        
       else if(AuthenticationHandler.authenticateUser(username, password)==true){
            accessEm employePanel =new accessEm();
            passwordField_1.setText(null);
                    textField_1.setText(null);
                    FlatAnimatedLafChange.showSnapshot();

                frame.getContentPane().remove(panel_1);
                frame.getContentPane().add(employePanel);
            

            
            frame.revalidate();
            frame.repaint();
            FlatAnimatedLafChange.hideSnapshotWithAnimation();  
            
        } 
        

        
        
        else {
           
            JOptionPane.showMessageDialog(null, "Invalid Login Details", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
    }
});
                 btnLogin.addMouseListener(new MouseAdapter() {
	    	  
	    	  @Override
	    	  
	    	  public void mouseEntered(MouseEvent e) {
	    		  btnLogin.setBackground(new Color(155,176,193));
	    	  }
	    	  
	    	 
	    	  
	    	  
	    	  @Override
	    	  
	    	  public void mouseExited(MouseEvent e) {
	    		 // btnLogin.setBackground(Color.GRAY);
	    	  }
	    	   
	      });


    }//GEN-LAST:event_jButton1ActionPerformed

    private void AboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutBtnActionPerformed
       aboutp k=new aboutp();
       showForm(k);
    }//GEN-LAST:event_AboutBtnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        accountp j=new accountp( );
        showForm(j);
      

      
    }//GEN-LAST:event_jButton6ActionPerformed

    private void EmployeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeBtnActionPerformed
       panel g =new panel();
        showForm(g) ;
    }//GEN-LAST:event_EmployeBtnActionPerformed

    private void GamesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GamesBtnActionPerformed
         panelg e=new panelg();
        showForm(e);
    }//GEN-LAST:event_GamesBtnActionPerformed

    private void FinanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinanceBtnActionPerformed
panelf j=new panelf();
showForm(j);


    }//GEN-LAST:event_FinanceBtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        calendarp l=new calendarp();
        showForm(l);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void GrievanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrievanceBtnActionPerformed
rapportAd n=new rapportAd();
showForm(n);
    }//GEN-LAST:event_GrievanceBtnActionPerformed
 public void showForm(JPanel component) {
       
       component.setVisible(true);
   
    ShowPanel.setLayout(new FlowLayout());
 
    ShowPanel.removeAll();
    
    ShowPanel.add(component);
   
    ShowPanel.repaint();

    ShowPanel.revalidate();
    

   }



 
 public void getSS() {
                         String sql = "SELECT username FROM employe WHERE username='ranim'";
    try (
            Connection conn = DriverManager.getConnection(url);
        PreparedStatement stmt = conn.prepareStatement(sql);
        ResultSet tt = stmt.executeQuery();
    ) {
        if (tt.next()) {
            // Fetch the username from the ResultSet
            String usernamee = tt.getString("username");
            
            ss.setText(usernamee);
        }
    } catch(SQLException ej) {
        ej.printStackTrace();
    }   
     
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutBtn;
    private javax.swing.JButton EmployeBtn;
    private javax.swing.JButton FinanceBtn;
    private javax.swing.JButton GamesBtn;
    private javax.swing.JButton GrievanceBtn;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel ShowPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel ss;
    // End of variables declaration//GEN-END:variables

}
