/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admingui;

import com.formdev.flatlaf.extras.FlatAnimatedLafChange;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author MSI_GS
 */
public class accessEm extends javax.swing.JPanel {

   
    /**
     * Creates new form accessEm
     */
    public accessEm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        LogoutBgtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        AboutBtn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ShowPanel = new javax.swing.JPanel();
        WorkVAcationBtn = new javax.swing.JButton();
        EventBtn = new javax.swing.JButton();
        GrievanceBtn = new javax.swing.JButton();
        TicketBtn = new javax.swing.JButton();

        MenuPanel.setBackground(new java.awt.Color(26, 55, 77));
        MenuPanel.setPreferredSize(new java.awt.Dimension(209, 800));

        jButton2.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(accessEm.class.getResource("/admingui/icons/ferris-wheels.png"))); // NOI18N
        jButton2.setText(" Operations");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        LogoutBgtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutBgtn.setIcon(new javax.swing.ImageIcon(accessEm.class.getResource("/admingui/icons/icons8-logout-32 (1).png"))); // NOI18N
        LogoutBgtn.setText("Logout    ");
        LogoutBgtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutBgtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBgtnActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(accessEm.class.getResource("/images/amusement-park (1).png"))); // NOI18N

        jButton5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(accessEm.class.getResource("/admingui/icons/calendar.png"))); // NOI18N
        jButton5.setText("  Calendar   ");
        jButton5.setToolTipText("");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        AboutBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        AboutBtn.setIcon(new javax.swing.ImageIcon(accessEm.class.getResource("/admingui/icons/info.png"))); // NOI18N
        AboutBtn.setText(" About      ");
        AboutBtn.setActionCommand(" About         ");
        AboutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutBtnActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(accessEm.class.getResource("/admingui/icons/user (1).png"))); // NOI18N
        jButton6.setText(" Account     ");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AboutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoutBgtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(AboutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                .addComponent(LogoutBgtn)
                .addGap(50, 50, 50))
        );

        jPanel4.setBackground(new java.awt.Color(26, 55, 77));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee");

        jLabel3.setIcon(new javax.swing.ImageIcon(accessEm.class.getResource("/images/man.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addContainerGap(1156, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ShowPanel.setPreferredSize(new java.awt.Dimension(1635, 808));

        WorkVAcationBtn.setForeground(new java.awt.Color(255, 255, 255));
        WorkVAcationBtn.setIcon(new javax.swing.ImageIcon(accessEm.class.getResource("/images/vcx.png"))); // NOI18N
        WorkVAcationBtn.setText("EmployeBtn");
        WorkVAcationBtn.setToolTipText("");
        WorkVAcationBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        WorkVAcationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkVAcationBtnActionPerformed(evt);
            }
        });

        EventBtn.setForeground(new java.awt.Color(0, 153, 153));
        EventBtn.setIcon(new javax.swing.ImageIcon(accessEm.class.getResource("/images/event.png"))); // NOI18N
        EventBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventBtnActionPerformed(evt);
            }
        });

        GrievanceBtn.setForeground(new java.awt.Color(255, 255, 255));
        GrievanceBtn.setIcon(new javax.swing.ImageIcon(accessEm.class.getResource("/images/ranim_1.png"))); // NOI18N
        GrievanceBtn.setText("EmployeBtn");
        GrievanceBtn.setToolTipText("");
        GrievanceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GrievanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrievanceBtnActionPerformed(evt);
            }
        });

        TicketBtn.setForeground(new java.awt.Color(255, 255, 255));
        TicketBtn.setIcon(new javax.swing.ImageIcon(accessEm.class.getResource("/images/rr.png"))); // NOI18N
        TicketBtn.setText("EmployeBtn");
        TicketBtn.setToolTipText("");
        TicketBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ShowPanelLayout = new javax.swing.GroupLayout(ShowPanel);
        ShowPanel.setLayout(ShowPanelLayout);
        ShowPanelLayout.setHorizontalGroup(
            ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowPanelLayout.createSequentialGroup()
                .addContainerGap(481, Short.MAX_VALUE)
                .addGroup(ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TicketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkVAcationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EventBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GrievanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(382, 382, 382))
        );
        ShowPanelLayout.setVerticalGroup(
            ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EventBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TicketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WorkVAcationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(GrievanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(141, 141, 141))
        );

        WorkVAcationBtn.setBorder(null);
        WorkVAcationBtn.setOpaque(false);
        WorkVAcationBtn.setBorder(null);
        WorkVAcationBtn.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ShowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1428, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    EmployeeOperation k=new  EmployeeOperation();
    showForm(k);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void LogoutBgtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBgtnActionPerformed
JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
    currentFrame.dispose();
JFrame frame = new JFrame("Digi-Parc");
frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
 frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
 frame.setVisible(true);
JPanel panel_1 = new Login.ImagePanel(accessEm.class.getResource("/admingui/icons/walid1.jpg"));
                   panel_1.setLayout(null);
	  	 	  	
        frame.getContentPane().add(panel_1);
        
       
        
	    
	    
	    JPanel lblda = new Login.ImagePanel(accessEm.class.getResource("/admingui/icons/b.jpg"));
            lblda.setLayout(null);
	    lblda.setBounds(340,120,835,600);
	    
	    panel_1.add(lblda);
	  
	
	

	 
	  JLabel lblNewLabel = new JLabel("LOGIN");
	    lblNewLabel.setForeground(Color.white);
	    lblNewLabel.setFont(new Font("Bookman Old Style", Font.BOLD, 50));
	    lblNewLabel.setBounds(335, 100, 200, 50);
	 
     
	   lblda.add(lblNewLabel);
	  
	  
	  
  
	  
	    
	    RoundJTextField textField_1  = new RoundJTextField(15, accessEm.class.getResource("/admingui/icons/user.png").getPath());
	    textField_1.setBounds(285, 200, 250, 28);
	    textField_1.setForeground(Color.black);
	    textField_1.setPlaceholder(" Username");
	    lblda.add(textField_1);
	    
	      
	      
	      RoundJTextFieldd passwordField_1  = new RoundJTextFieldd(15, accessEm.class.getResource("/images/password.png").getPath());
	     passwordField_1.setBounds(284, 265, 250, 28);
	    passwordField_1.setPlaceholder(" Password");
	    lblda.add(passwordField_1);
	    
	   
	      
	 

	    MyButton btnLogin = new MyButton();
	    btnLogin.setText("Login");
        btnLogin.setRadius(23);
        btnLogin.setBorderPainted(false);
	    btnLogin.setBackground(Color.white);
	    btnLogin.setForeground(Color.black);
	    
	   btnLogin.setBounds(310, 360, 200, 30); 
	    btnLogin.setFocusPainted(false);
	    lblda.add(btnLogin);

	    

	    JCheckBox showpass = new JCheckBox("Show password");
	      
	      
	      showpass.setFont(new Font("Sitka Small", Font.PLAIN, 13));
	      
	      showpass.setOpaque(false);
	      showpass.setBorderPainted(false);
	      showpass.setFocusPainted(false);
              showpass.setForeground(Color.white);
	      showpass.setBounds(350, 320, 120, 21);
	      lblda.add(showpass);

frame.getContentPane().add(panel_1);

frame.pack();
frame.setLocationRelativeTo(null);
frame.setVisible(true);
showpass.addActionListener(new ActionListener() {
	          public void actionPerformed(ActionEvent e) {
	              if(showpass.isSelected()) {
	               (passwordField_1).setEchoChar((char)0);
	              } else {
	               passwordField_1.setEchoChar('•');
	              }
	          }
	      });
	       btnLogin.addActionListener(new ActionListener() {
    public void actionPerformed(ActionEvent e) {
        String username = textField_1.getText();
        String password = new String(passwordField_1.getText());
        
        
        if (AuthenticationHandler.authenticateAdmin(username, password)==true) {
                    accessAdmin adminPanel = new accessAdmin();
                    passwordField_1.setText(null);
                    textField_1.setText(null);
            FlatAnimatedLafChange.showSnapshot();

                frame.getContentPane().remove(panel_1);
                frame.getContentPane().add(adminPanel);
            

            
            frame.revalidate();
            frame.repaint();
            FlatAnimatedLafChange.hideSnapshotWithAnimation();  
        } 
        
       else if(AuthenticationHandler.authenticateUser(username, password)==true){
            accessEm employePanel =new accessEm();
            passwordField_1.setText(null);
                    textField_1.setText(null);
                    FlatAnimatedLafChange.showSnapshot();

                frame.getContentPane().remove(panel_1);
                frame.getContentPane().add(employePanel);
            

            
            frame.revalidate();
            frame.repaint();
            FlatAnimatedLafChange.hideSnapshotWithAnimation();  
            
        } 
        

        
        
        else {
           
            JOptionPane.showMessageDialog(null, "Invalid Login Details", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
    }
});
                 btnLogin.addMouseListener(new MouseAdapter() {
	    	  
	    	  @Override
	    	  
	    	  public void mouseEntered(MouseEvent e) {
	    		  btnLogin.setBackground(new Color(155,176,193));
	    	  }
	    	  
	    	 
	    	  
	    	  
	    	  @Override
	    	  
	    	  public void mouseExited(MouseEvent e) {
	    		 // btnLogin.setBackground(Color.GRAY);
	    	  }
	    	   
	      });
        
    }//GEN-LAST:event_LogoutBgtnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
accountp p =new accountp();
showForm(p);
  // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void AboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutBtnActionPerformed
 aboutp k=new aboutp();
       showForm(k);        // TODO add your handling code here:
    }//GEN-LAST:event_AboutBtnActionPerformed

    private void EventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventBtnActionPerformed
        events u=new events();
        showForm(u);
    }//GEN-LAST:event_EventBtnActionPerformed

    private void GrievanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrievanceBtnActionPerformed
 Grievances b=new Grievances();
        showForm(b);        // TODO add your handling code here:
    }//GEN-LAST:event_GrievanceBtnActionPerformed

    private void TicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketBtnActionPerformed
Tick ti=new Tick();
showForm(ti);


    }//GEN-LAST:event_TicketBtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
calendarp imen=new calendarp();
showForm(imen);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void WorkVAcationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkVAcationBtnActionPerformed
     WorkVacation l=new WorkVacation();
     showForm(l);
    }//GEN-LAST:event_WorkVAcationBtnActionPerformed

   public void showForm(JPanel component) {
    // Clear the current content of the panel
       component.setVisible(true);
    
    ShowPanel.setLayout(new FlowLayout());
 
    ShowPanel.removeAll();
    
    ShowPanel.add(component);
   
    ShowPanel.repaint();

    ShowPanel.revalidate();
    
   }
   
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutBtn;
    private javax.swing.JButton EventBtn;
    private javax.swing.JButton GrievanceBtn;
    private javax.swing.JButton LogoutBgtn;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel ShowPanel;
    private javax.swing.JButton TicketBtn;
    private javax.swing.JButton WorkVAcationBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
