/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admingui;

import raven.toast.Notifications;

import javax.swing.*;
import javax.swing.border.Border;
import java.awt.*;
import java.sql.*;

/**
 *
 * @author ASUS
 */
public class addGame extends javax.swing.JPanel {
Border default_border = BorderFactory.createMatteBorder(0, 0, 3, 0, new Color(153,153,153));
    Border red_border = BorderFactory.createMatteBorder(0, 0, 3, 0, Color.blue);
    private static final String url =
            "jdbc:sqlite:" + System.getProperty("user.dir") + "/parc.db";

    Connection con;
    /**
     * Creates new form addGame
     */
    public addGame() {
         
        initComponents();
        try {

            con = DriverManager.getConnection(url);

        } catch (SQLException e) {

            e.printStackTrace();
        }
        jTextField2.setEditable(false);
        getid();
        
            jButton2.setBorder(default_border);
         jButton6.setBorder(default_border); 
         jButton8.setBorder(default_border);
         setButtonBorder(jButton2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
      public void setButtonBorder(JButton button)
    {
        
            
            jButton2.setBorder(default_border);
            jButton6.setBorder(default_border);
            jButton8.setBorder(default_border);
            jButton2.setForeground(new Color(153,153,153));
            jButton6.setForeground(new Color(153,153,153));
            jButton8.setForeground(new Color(153,153,153));
        
        
        
        button.setBorder(red_border);
        button.setForeground(Color.black);
     
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        crazyPanel1 = new admingui.CrazyPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ADD = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 153, 153));
        jButton2.setText("Add Game");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 153, 153));
        jButton6.setText("Show list Games");
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(153, 153, 153));
        jButton8.setText("Remove Game");
        jButton8.setBorder(null);
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        crazyPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Game Details");
        crazyPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 150, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("ID:");
        crazyPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 40, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Game Name:");
        crazyPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 100, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Description:");
        crazyPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 110, 20));

        jTextField2.setForeground(new java.awt.Color(102, 102, 102));
        jTextField2.setText("Enter ID");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        crazyPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 70, -1));

        jTextField3.setForeground(new java.awt.Color(102, 102, 102));
        jTextField3.setText("Describe.....");
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        crazyPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 280, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Limited Age:");
        crazyPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 100, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Duration:");
        crazyPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 80, 20));

        ADD.setBackground(new Color(193,225,193));
        ADD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ADD.setText("ADD");
        ADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADDMouseExited(evt);
            }
        });
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        crazyPanel1.add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        jTextField4.setForeground(new java.awt.Color(102, 102, 102));
        jTextField4.setText("Enter the name of game");
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        crazyPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 180, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "25", "24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9", "8", "7", "6", "5", "4", "3" }));
        crazyPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jTextField5.setForeground(new java.awt.Color(102, 102, 102));
        jTextField5.setText("Enter DA");
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        crazyPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 90, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Capacity:");
        crazyPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 70, 20));

        jTextField6.setForeground(new java.awt.Color(102, 102, 102));
        jTextField6.setText("Enter min");
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });
        crazyPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setText("Enter Kg");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        crazyPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 110, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setText("Price:");
        crazyPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 50, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(crazyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        setButtonBorder(jButton2);

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered

    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited

    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        ListGame f=new ListGame();
        setButtonBorder(jButton6);
        showForm(f);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        RemoveG l=new RemoveG();
        setButtonBorder(jButton8);
        showForm(l);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        if(jTextField2.getText().equals("Enter ID")){
            jTextField2.setText("");
            jTextField2.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
          if(jTextField2.getText().equals("")){
            jTextField2.setText("Enter ID");
            jTextField2.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
       if(jTextField4.getText().equals("Enter the name of game")){
            jTextField4.setText("");
            jTextField4.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
          if(jTextField4.getText().equals("")){
            jTextField4.setText("Enter the name of game");
            jTextField4.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
       if(jTextField3.getText().equals("Describe.....")){
           jTextField3.setText("");
           jTextField3.setForeground(Color.black);
       }
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
           if(jTextField3.getText().equals("")){
           jTextField3.setText("Describe.....");
           jTextField3.setForeground(new Color(102,102,102));
       }
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        if(jTextField1.getText().equals("Enter Kg")){
           jTextField1.setText("");
           jTextField1.setForeground(Color.black);
       }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
          if(jTextField1.getText().equals("")){
           jTextField1.setText("Enter Kg");
           jTextField1.setForeground(new Color(102,102,102));
       }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        if(jTextField5.getText().equals("Enter DA")){
           jTextField5.setText("");
           jTextField5.setForeground(Color.black);
       }
        
    }//GEN-LAST:event_jTextField5FocusGained

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        if(jTextField5.getText().equals("")){
           jTextField5.setText("Enter DA");
           jTextField5.setForeground(new Color(102,102,102));
       }
    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusGained
         if(jTextField6.getText().equals("Enter min")){
           jTextField6.setText("");
           jTextField6.setForeground(Color.black);
       }
    }//GEN-LAST:event_jTextField6FocusGained

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
         if(jTextField6.getText().equals("")){
           jTextField6.setText("Enter min");
           jTextField6.setForeground(new Color(102,102,102));
       }
    }//GEN-LAST:event_jTextField6FocusLost

    private void ADDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseEntered
         ADD.setBackground(new Color(66,255,74));
    }//GEN-LAST:event_ADDMouseEntered

    private void ADDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseExited
       ADD.setBackground(new Color(193,225,193));
    }//GEN-LAST:event_ADDMouseExited

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
     String id = jTextField2.getText();
String name = jTextField4.getText();
String description = jTextField3.getText();
String ageLimit = jComboBox3.getSelectedItem().toString();
String capacity = jTextField1.getText();
String price = jTextField5.getText();
String duration = jTextField6.getText();

if (id.isEmpty() || name.isEmpty() || description.isEmpty() || capacity.isEmpty() || price.isEmpty() || duration.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please fill in all the fields.", "Error", JOptionPane.ERROR_MESSAGE);
} else {
    String sql =
            "INSERT INTO attraction " +
                    "(IdAtt, NomAtt, Description, Cout, Disponibilite, Capacite, Age_Limite, Duree, IDman) " +
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
    try (Connection conn = DriverManager.getConnection(url);
         PreparedStatement stmt = conn.prepareStatement(sql);) {
        stmt.setString(1, id);
        stmt.setString(2, name);
        stmt.setString(3, description);
        stmt.setString(4, price);
        stmt.setBoolean(5, true); // Assuming Disponibilite is a boolean field and should always be true
        stmt.setString(6, capacity);
        stmt.setString(7, ageLimit);
        stmt.setString(8, duration);
        stmt.setInt(9, 1111);

        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to add this attraction?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            int rowsInserted = stmt.executeUpdate();
            if (rowsInserted > 0) {
                Notifications.getInstance().show(Notifications.Type.INFO, Notifications.Location.TOP_CENTER, "Attraction added successfully!");
                jTextField1.setForeground(new Color(102, 102, 102));
                jTextField2.setForeground(new Color(102, 102, 102));
                jTextField3.setForeground(new Color(102, 102, 102));
                jTextField4.setForeground(new Color(102, 102, 102));
                jTextField5.setForeground(new Color(102, 102, 102));
                jTextField6.setForeground(new Color(102, 102, 102));

                jTextField2.setText("Enter ID");
                jTextField4.setText("Enter the name of game");
                jTextField3.setText("Describe.....");
                jTextField1.setText("Enter Kg");
                jTextField5.setText("Enter DA");
                jTextField6.setText("Enter min");
                getid();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to insert new attraction!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

         
    }//GEN-LAST:event_ADDActionPerformed
  public void showForm(JPanel component) {
    // Clear the current content of the panel
    removeAll();

    // Set layout manager to FlowLayout
    setLayout(new FlowLayout());

    // Add the new component to the panel
    add(component);

    // Repaint and revalidate the panel
    repaint();
    revalidate();
}

   private void getid(){
          String sql = "SELECT MAX(IdAtt) + 1 AS NextId FROM attraction";
try (Connection conn = DriverManager.getConnection(url);
     PreparedStatement stmt = conn.prepareStatement(sql)) {        

    ResultSet tt = stmt.executeQuery();
    if (tt.next()) {
        int nextId = tt.getInt("NextId");
        // Assuming jTextField is your JTextField instance
        jTextField2.setText(String.valueOf(nextId));
    } else {
        // Handle the case when there are no records
        jTextField2.setText("1"); // Assuming you want to start from 1 if there are no records
    }
} catch (SQLException e) {
    // Handle SQL exception
    e.printStackTrace();
}
        
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private admingui.CrazyPanel crazyPanel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
