/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admingui;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author MSI_GS
 */
public class adminOperationPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form adminOperationPanel
     */
    public adminOperationPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShowPanel = new javax.swing.JPanel();
        EmployeBtn = new javax.swing.JButton();
        GamesBtn = new javax.swing.JButton();
        FinanceBtn = new javax.swing.JButton();
        GrievanceBtn = new javax.swing.JButton();

        EmployeBtn.setForeground(new java.awt.Color(255, 255, 255));
        EmployeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mml.png"))); // NOI18N
        EmployeBtn.setText("EmployeBtn");
        EmployeBtn.setToolTipText("");
        EmployeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmployeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeBtnActionPerformed(evt);
            }
        });

        GamesBtn.setForeground(new java.awt.Color(0, 153, 153));
        GamesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gdf.png"))); // NOI18N
        GamesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GamesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GamesBtnActionPerformed(evt);
            }
        });

        FinanceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eeee.png"))); // NOI18N
        FinanceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FinanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinanceBtnActionPerformed(evt);
            }
        });

        GrievanceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ranim_1.png"))); // NOI18N
        GrievanceBtn.setText("jButton10");
        GrievanceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GrievanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrievanceBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ShowPanelLayout = new javax.swing.GroupLayout(ShowPanel);
        ShowPanel.setLayout(ShowPanelLayout);
        ShowPanelLayout.setHorizontalGroup(
            ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowPanelLayout.createSequentialGroup()
                .addGap(462, 462, 462)
                .addGroup(ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FinanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GrievanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GamesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(591, Short.MAX_VALUE))
        );
        ShowPanelLayout.setVerticalGroup(
            ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GamesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GrievanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FinanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1635, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ShowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(ShowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeBtnActionPerformed
       panel x=new panel();
        showForm(x);
    }//GEN-LAST:event_EmployeBtnActionPerformed

    private void GamesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GamesBtnActionPerformed
        panelg c=new panelg();
        showForm(c);
    }//GEN-LAST:event_GamesBtnActionPerformed

    private void FinanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinanceBtnActionPerformed
panelf k=new panelf();
showForm(k);
    }//GEN-LAST:event_FinanceBtnActionPerformed

    private void GrievanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrievanceBtnActionPerformed
       rapportAd l=new rapportAd();
       showForm(l);
    }//GEN-LAST:event_GrievanceBtnActionPerformed

 public void showForm(JPanel component) {
       
        component.setVisible(true);
    
    ShowPanel.setLayout(new FlowLayout());
 
    ShowPanel.removeAll();
    
    ShowPanel.add(component);
   ShowPanel.revalidate();
    ShowPanel.repaint();

    
    
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmployeBtn;
    private javax.swing.JButton FinanceBtn;
    private javax.swing.JButton GamesBtn;
    private javax.swing.JButton GrievanceBtn;
    private javax.swing.JPanel ShowPanel;
    // End of variables declaration//GEN-END:variables
}
