/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admingui;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author imoun
 */
public class EmployeeOperation extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeOperation
     */
    public EmployeeOperation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShowPanel = new javax.swing.JPanel();
        WorkVAcationBtn = new javax.swing.JButton();
        EventBtn = new javax.swing.JButton();
        GrievanceBtn = new javax.swing.JButton();
        TicketBtn = new javax.swing.JButton();

        ShowPanel.setPreferredSize(new java.awt.Dimension(1463, 740));

        WorkVAcationBtn.setForeground(new java.awt.Color(255, 255, 255));
        WorkVAcationBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vcx.png"))); // NOI18N
        WorkVAcationBtn.setText("EmployeBtn");
        WorkVAcationBtn.setToolTipText("");
        WorkVAcationBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        WorkVAcationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkVAcationBtnActionPerformed(evt);
            }
        });

        EventBtn.setForeground(new java.awt.Color(0, 153, 153));
        EventBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/event.png"))); // NOI18N
        EventBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventBtnActionPerformed(evt);
            }
        });

        GrievanceBtn.setForeground(new java.awt.Color(255, 255, 255));
        GrievanceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ranim_1.png"))); // NOI18N
        GrievanceBtn.setText("EmployeBtn");
        GrievanceBtn.setToolTipText("");
        GrievanceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GrievanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrievanceBtnActionPerformed(evt);
            }
        });

        TicketBtn.setForeground(new java.awt.Color(255, 255, 255));
        TicketBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rr.png"))); // NOI18N
        TicketBtn.setText("EmployeBtn");
        TicketBtn.setToolTipText("");
        TicketBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ShowPanelLayout = new javax.swing.GroupLayout(ShowPanel);
        ShowPanel.setLayout(ShowPanelLayout);
        ShowPanelLayout.setHorizontalGroup(
            ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowPanelLayout.createSequentialGroup()
                .addContainerGap(419, Short.MAX_VALUE)
                .addGroup(ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TicketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkVAcationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShowPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(GrievanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ShowPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(EventBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(491, 491, 491))
        );
        ShowPanelLayout.setVerticalGroup(
            ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TicketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EventBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WorkVAcationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GrievanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(141, 141, 141))
        );

        WorkVAcationBtn.setBorder(null);
        WorkVAcationBtn.setOpaque(false);
        WorkVAcationBtn.setBorder(null);
        WorkVAcationBtn.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1475, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ShowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1475, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ShowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void WorkVAcationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkVAcationBtnActionPerformed
        WorkVacation vc =new WorkVacation();
        showForm(vc);
    }//GEN-LAST:event_WorkVAcationBtnActionPerformed

    private void EventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventBtnActionPerformed
        events u=new events();
        showForm(u);
    }//GEN-LAST:event_EventBtnActionPerformed

    private void GrievanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrievanceBtnActionPerformed
       Grievances l=new Grievances();
       showForm(l);
    }//GEN-LAST:event_GrievanceBtnActionPerformed

    private void TicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketBtnActionPerformed
        Tick ti=new Tick();
        showForm(ti);

    }//GEN-LAST:event_TicketBtnActionPerformed

    
    
   public void showForm(JPanel component) {
       
        component.setVisible(true);
    
    ShowPanel.setLayout(new FlowLayout());
 
    ShowPanel.removeAll();
    
    ShowPanel.add(component);
   
    ShowPanel.repaint();

    ShowPanel.revalidate();
    
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EventBtn;
    private javax.swing.JButton GrievanceBtn;
    private javax.swing.JPanel ShowPanel;
    private javax.swing.JButton TicketBtn;
    private javax.swing.JButton WorkVAcationBtn;
    // End of variables declaration//GEN-END:variables

}