package admingui;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import javax.swing.*;
import java.awt.*;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;

/**
 *
 * @author imoun
 */
public class events extends javax.swing.JPanel {

    /**
     * Creates new form events
     */
    public events() {
        initComponents();
                buttonGroup1.add(jRadioButton3);
                buttonGroup1.add(jRadioButton4);
                        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ShowPanel = new javax.swing.JPanel();
        crazyPanel1 = new admingui.CrazyPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        crazyPanel2 = new admingui.CrazyPanel();
        crazyPanel3 = new admingui.CrazyPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jSpinField2 = new com.toedter.components.JSpinField();
        jLabel12 = new javax.swing.JLabel();
        jSpinField1 = new com.toedter.components.JSpinField();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1463, 740));

        crazyPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        crazyPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 190, -1));
        crazyPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 0));
        crazyPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));
        crazyPanel1.add(crazyPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        crazyPanel3.setForeground(new java.awt.Color(102, 102, 102));
        crazyPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setText("Event Request ");
        crazyPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 370, 60));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("End Of The Event :");
        crazyPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 150, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Event Name :");
        crazyPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 200, 30));

        jTextField8.setForeground(new java.awt.Color(102, 102, 102));
        jTextField8.setText("Enter name");
        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField8FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField8FocusLost(evt);
            }
        });
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        crazyPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 150, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Start Of The Event :");
        crazyPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, 50));

        jTextField10.setForeground(new java.awt.Color(102, 102, 102));
        jTextField10.setText("Organizer...");
        jTextField10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField10FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField10FocusLost(evt);
            }
        });
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        crazyPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 150, 30));
        crazyPanel3.add(jSpinField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, -1, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Start Time Of The Event :");
        crazyPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 190, 50));
        crazyPanel3.add(jSpinField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("End Time  Of The Event :");
        crazyPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 170, 50));

        jDateChooser3.setPreferredSize(new java.awt.Dimension(64, 22));
        crazyPanel3.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 150, 30));

        jDateChooser2.setPreferredSize(new java.awt.Dimension(64, 22));
        crazyPanel3.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 150, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Organizer Name :");
        crazyPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 160, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setText("Details :");
        crazyPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 180, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 153, 153));
        crazyPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 750, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Does Your Event Last One Day? ");
        crazyPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 250, 30));

        jRadioButton3.setText("Yes");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        crazyPanel3.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        jRadioButton4.setText("No");
        crazyPanel3.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setText("Number Of Participants Expected  :");
        crazyPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 270, 30));

        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setText("Enter number");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        crazyPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 120, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setText("Number Of Visitors Expected  :");
        crazyPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 250, 30));

        jTextField3.setForeground(new java.awt.Color(102, 102, 102));
        jTextField3.setText("Enter number");
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        crazyPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 120, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setText("Target Audience  :");
        crazyPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 250, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Children", "Teenagers", "Adults", "Elderly", "Families" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        crazyPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 120, -1));

        jTextField2.setForeground(new java.awt.Color(102, 102, 102));
        jTextField2.setText("Other...");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        crazyPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 110, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setText("Other Specifications And Descriptions :");
        crazyPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 300, 30));

        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea2.setRows(5);
        jTextArea2.setText("Typing...");
        jTextArea2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextArea2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea2FocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea2);

        crazyPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 590, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Organizer Signature :");
        crazyPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 200, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("PRINT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        crazyPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, -1));

        crazyPanel1.add(crazyPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 950, 980));

        javax.swing.GroupLayout ShowPanelLayout = new javax.swing.GroupLayout(ShowPanel);
        ShowPanel.setLayout(ShowPanelLayout);
        ShowPanelLayout.setHorizontalGroup(
            ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ShowPanelLayout.setVerticalGroup(
            ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 167, Short.MAX_VALUE)
                .addComponent(ShowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ShowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField10FocusLost
        if(jTextField10.getText().equals("")){
            jTextField10.setText("Organizer...");
            jTextField10.setForeground(new Color(102,102,102));
         }
    }//GEN-LAST:event_jTextField10FocusLost

    private void jTextField10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField10FocusGained
        if(jTextField10.getText().equals("Organizer...")){
            jTextField10.setText("");
            jTextField10.setForeground(Color.black);
         }
    }//GEN-LAST:event_jTextField10FocusGained

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusLost
         if(jTextField8.getText().equals("")){
            jTextField8.setText("Enter name");
            jTextField8.setForeground(new Color(102,102,102));
         }
    }//GEN-LAST:event_jTextField8FocusLost

    private void jTextField8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusGained
        if(jTextField8.getText().equals("Enter name")){
            jTextField8.setText("");
            jTextField8.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField8FocusGained

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextArea2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea2FocusGained
    if(jTextArea2.getText().equals("Typing...")){
     jTextArea2.setText("");   
     jTextArea2.setForeground(Color.black);
    }
    }//GEN-LAST:event_jTextArea2FocusGained

    private void jTextArea2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea2FocusLost
        if(jTextArea2.getText().equals("")){
     jTextArea2.setText("Typing...");   
     jTextArea2.setForeground(new Color(102,102,102));
    }
    }//GEN-LAST:event_jTextArea2FocusLost

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
         if(jTextField1.getText().equals("Enter number")){
     jTextField1.setText("");   
     jTextField1.setForeground(Color.black);
    }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
         if(jTextField1.getText().equals("")){
     jTextField1.setText("Enter number");   
     jTextField1.setForeground(new Color(102,102,102));
    }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
            if(jTextField3.getText().equals("Enter number")){
     jTextField3.setText("");   
     jTextField3.setForeground(Color.black);
    }
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
            if(jTextField3.getText().equals("")){
     jTextField3.setText("Enter number");   
     jTextField3.setForeground(new Color(102,102,102));
    }
    }//GEN-LAST:event_jTextField3FocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PrinterJob job = PrinterJob.getPrinterJob();
job.setPrintable(new Printable() {
    public int print(Graphics g, PageFormat pf, int pageIndex) {
        if (pageIndex > 0) {
            return NO_SUCH_PAGE;
        }

        Graphics2D g2d = (Graphics2D) g;
        g2d.translate(pf.getImageableX(), pf.getImageableY());

        // Check if the panel has content to print
        if (crazyPanel1.getComponentCount() == 0) {
            System.out.println("Nothing to print.");
            return NO_SUCH_PAGE;
        }

        // Enhance graphics rendering quality
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

        // Draw the panel content to print
        crazyPanel1.printAll(g);

        return PAGE_EXISTS;
    }
});

boolean ok = job.printDialog();
if (ok) {
    try {
        job.print();
    } catch (PrinterException ex) {
        // Handle printing errors
        JOptionPane.showMessageDialog(null, "Printing error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        System.out.println("Printing error: " + ex.getMessage());
    }
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        if(jTextField2.getText().equals("Other...")){
            jTextField2.setText("");
            jTextField2.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
       if(jTextField2.getText().equals("")){
            jTextField2.setText("Other...");
            jTextField2.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jTextField2FocusLost

    
     public void showForm(JPanel component) {
    // Clear the current content of the panel
       component.setVisible(true);
    
    ShowPanel.setLayout(new FlowLayout());
 
    ShowPanel.removeAll();
    
    ShowPanel.add(component);
   
    ShowPanel.repaint();

    ShowPanel.revalidate();
    
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ShowPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private admingui.CrazyPanel crazyPanel1;
    private admingui.CrazyPanel crazyPanel2;
    private admingui.CrazyPanel crazyPanel3;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private com.toedter.components.JSpinField jSpinField1;
    private com.toedter.components.JSpinField jSpinField2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
