/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admingui;

import raven.toast.Notifications;

import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.util.Date;

import static admingui.ListPanel.*;

/**
 *
 * @author imoun
 */
public class Grievances extends javax.swing.JPanel {
private DefaultComboBoxModel<String> employeeModel;
    /**
     * Creates new form Grievances
     */
    String url ="jdbc:sqlite:parc.db";

    Connection con;
    public Grievances() {
        initComponents();
        try {

            con = DriverManager.getConnection(url);

        } catch (SQLException e) {

            e.printStackTrace();
        }
         employeeModel = new DefaultComboBoxModel<>();
        jTextField2.setEditable(false);
        jTextField1.setEditable(false);
        populateEmployeeComboBox();
        jTextField4.setEditable(false);
        jTextField4.setText(getManagerName());
        getid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShowPanel = new javax.swing.JPanel();
        crazyPanel1 = new admingui.CrazyPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();

        crazyPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setText("Grievance");
        crazyPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 350, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        crazyPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 30));

        jDateChooser2.setToolTipText("DD/MM/YY");
        jDateChooser2.setPreferredSize(new java.awt.Dimension(64, 22));
        crazyPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 150, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        crazyPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 190, -1));
        crazyPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 0));
        crazyPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 153, 153));
        crazyPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 640, 30));

        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea2.setRows(5);
        jTextArea2.setText("Typing...");
        jTextArea2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextArea2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea2FocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea2);

        crazyPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 760, 200));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Send To");
        crazyPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 90, 30));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        crazyPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 180, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setText("ID:");
        crazyPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 90, 30));

        jTextField4.setText("Mr.");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        crazyPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 170, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Full Name:");
        crazyPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("SEND");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        crazyPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        crazyPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 90, 30, 60));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        crazyPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 110, 30));

        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setText("N°");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        crazyPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 110, 30));

        javax.swing.GroupLayout ShowPanelLayout = new javax.swing.GroupLayout(ShowPanel);
        ShowPanel.setLayout(ShowPanelLayout);
        ShowPanelLayout.setHorizontalGroup(
            ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowPanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        ShowPanelLayout.setVerticalGroup(
            ShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ShowPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ShowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
 String selectedId = (String) jComboBox1.getSelectedItem();
            if (selectedId != null) {
                String name = getEmployeeName(selectedId);
                jTextField2.setText(name);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextArea2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea2FocusGained
      if(jTextArea2.getText().equals("Typing...")){
            jTextArea2.setText("");
            jTextArea2.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextArea2FocusGained

    private void jTextArea2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea2FocusLost
        if(jTextArea2.getText().equals("")){
            jTextArea2.setText("Typing...");
            jTextArea2.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jTextArea2FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String selectedEmployeeId = (String) jComboBox1.getSelectedItem();
    String selectedEmployeeName = jTextField2.getText();
    String selectedManagerName = jTextField4.getText();
    String grievanceDescription = jTextArea2.getText();
    Date de=jDateChooser2.getDate();
    String n=jTextField1.getText();
     try (Connection conn = DriverManager.getConnection(url)) {
        String sql = "INSERT INTO rapport (NumRapport,idEmp, nEmp, DateEcrit, Description) VALUES (?,?, ?, ?, ?)";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1, n);
        stmt.setString(2, selectedEmployeeId);
        stmt.setString(3,selectedEmployeeName ); // Current date
         stmt.setString(
                 4,
                 new java.text.SimpleDateFormat("yyyy-MM-dd")
                         .format(de)
         );
        stmt.setString(5,grievanceDescription);
        int rowsInserted = stmt.executeUpdate();
        if (rowsInserted > 0) {
            Notifications.getInstance().show(Notifications.Type.INFO, Notifications.Location.TOP_CENTER, "Grievance Sent!");
            System.out.println("A new grievance was inserted successfully.");
            jTextField1.setForeground(new Color(102,102,102));
            jTextArea2.setForeground(new Color(102,102,102));
            
            getid();
            jTextArea2.setText("Typing...");
            jDateChooser2.setDate(null);
            
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
      if(jTextField1.getText().equals("N°")){
            jTextField1.setText("");
            jTextField1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if(jTextField1.getText().equals("")){
            jTextField1.setText("N°");
            jTextField1.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
public void showForm(JPanel component) {
       
        component.setVisible(true);
    
    ShowPanel.setLayout(new FlowLayout());
 
    ShowPanel.removeAll();
    
    ShowPanel.add(component);
   ShowPanel.revalidate();
    ShowPanel.repaint();
   }
 private void populateEmployeeComboBox() {
        // Clear previous elements
         String sql = "SELECT IdEmp,NomEmp,PrenomEmp FROM employe";
        employeeModel.removeAllElements();
        try (Connection conn = DriverManager.getConnection(url);
                PreparedStatement stmt = conn.prepareStatement(sql);
                ResultSet tt = stmt.executeQuery()) {
           
            
           
            while (tt.next()) {
                System.out.println(tt.getString("IdEmp"));
                String id = tt.getString("IdEmp");
                employeeModel.addElement(id);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        jComboBox1.setModel(employeeModel);
    }
private String getEmployeeName(String id) {
        String name = "";
        String pren="";
        try (Connection conn = DriverManager.getConnection(url)) {
            String sql = "SELECT NomEmp,PrenomEmp FROM employe WHERE IdEmp = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, id);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                name = rs.getString("NomEmp");
                pren=rs.getString("PrenomEmp");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        name = name+" "+pren;
        return name;
    }

private String getManagerName(){
    String name="";
    String pren="";
    try (Connection conn = DriverManager.getConnection(url)) {
            String sql = "SELECT Nom,Prenom FROM manager";
            PreparedStatement stmt = conn.prepareStatement(sql);
//            stmt.setString(1, "Nom");
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                name = rs.getString("Nom");
                pren = rs.getString("Prenom");
               
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    name="Mr/Mrs."+name +" "+ pren;
    return name;
}

 private void getid(){
          String sql = "SELECT MAX(NumRapport) + 1 AS NextId FROM rapport";
try (Connection conn = DriverManager.getConnection(url);
     PreparedStatement stmt = conn.prepareStatement(sql)) {        

    ResultSet tt = stmt.executeQuery();
    if (tt.next()) {
        int nextId = tt.getInt("NextId");
        // Assuming jTextField is your JTextField instance
        jTextField1.setText(String.valueOf(nextId));
    } else {
        // Handle the case when there are no records
        jTextField1.setText("1"); // Assuming you want to start from 1 if there are no records
    }
} catch (SQLException e) {
    // Handle SQL exception
    e.printStackTrace();
}
        
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ShowPanel;
    private admingui.CrazyPanel crazyPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
