/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admingui;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.SQLException;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacLightLaf;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
/**
 *
 * @author MSI_GS
 */
public class Login extends javax.swing.JFrame {
private static JPanel panel_1;
private static JFrame frame = new JFrame();
	private static final String url =
			"jdbc:sqlite:" + System.getProperty("user.dir") + "/parc.db";

	Connection con ;
         accessAdmin p=new accessAdmin();
         private JLabel f;
    /**
     * Creates new fprorm Login
     */
    public Login() {
         
        initComponents();





			try {

				con = DriverManager.getConnection(url);

			} catch (SQLException e) {

				e.printStackTrace();
			}



    }
    
     public JLabel getF() {
        return f;
    }
    
   
    
     
     public static void showForm(JPanel component) {
       FlatAnimatedLafChange.showSnapshot();
        component.setVisible(true);
    
    panel_1.setLayout(new FlowLayout());
 
   panel_1.removeAll();
    
   panel_1.add(component);
   
    panel_1.repaint();

    panel_1.revalidate();
    FlatAnimatedLafChange.hideSnapshotWithAnimation();
   }

	static class ImagePanel extends JPanel {
		private Image backgroundImage;

		public ImagePanel(java.net.URL imageURL) {
			this.backgroundImage = new ImageIcon(imageURL).getImage();
		}

	    @Override
	    protected void paintComponent(Graphics g) {
	        super.paintComponent(g);
	        g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
	    }

	    @Override
	    public Dimension getPreferredSize() {
	        if (backgroundImage != null) {
	            return new Dimension(backgroundImage.getWidth(this), backgroundImage.getHeight(this));
	        } else {
	            return super.getPreferredSize();
	        }
	    }
	}
   
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
		try {
			FlatRobotoFont.install();
			UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
			FlatMacLightLaf.setup();
		} catch (Exception e) {
			e.printStackTrace();
		}

 
        	frame = new JFrame("Digi-Parc");
	  		
	  		frame.setSize(800, 600);
	  		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        
	  		frame.setLocationRelativeTo(null);
	  		frame.setVisible(true);
	  		
                        java.net.URL iconURL = Login.class.getResource("/admingui/icons/walid.jpg");
	                        Image icon = (iconURL != null) ? Toolkit.getDefaultToolkit().getImage(iconURL) : null;
        
        // Set the icon for the JFrame
        frame.setIconImage(icon);




		panel_1 = new ImagePanel(Login.class.getResource("/admingui/icons/walid1.jpg"));

		panel_1.setLayout(null);
	  	 	  	
        frame.getContentPane().add(panel_1);
        
       
        
	    
	    
	    JPanel lblda = new ImagePanel(Login.class.getResource("/admingui/icons/b.jpg"));
            lblda.setLayout(null);
	    lblda.setBounds(340,120,835,600);
	    
	    panel_1.add(lblda);
	  
	
//	  JPanel st=new ImagePanel("C:\\Users\\MSI_GS\\Downloads\\walid.jpg");
//	  st.setLayout(null);
//	  st.setBounds(340,120,250,600);
//	  
//	  panel_1.add(st);
//	

	 
	  JLabel lblNewLabel = new JLabel("LOGIN");
	    lblNewLabel.setForeground(Color.white);
	    lblNewLabel.setFont(new Font("Bookman Old Style", Font.BOLD, 50));
	    lblNewLabel.setBounds(335, 100, 200, 50);
	 
     
	   lblda.add(lblNewLabel);
	  
	  
	  
  
	  
	    
	    RoundJTextField textField_1  = new RoundJTextField(15, Login.class.getResource("/admingui/icons/icons8-user-24.png").getPath());
	    textField_1.setBounds(285, 200, 250, 28);
	    textField_1.setForeground(Color.black);
	    textField_1.setPlaceholder(" Username");
	    lblda.add(textField_1);
	    
	      
	      
	      RoundJTextFieldd passwordField_1  = new RoundJTextFieldd(15, Login.class.getResource("/admingui/icons/icons8-lock-24.png").getPath());
	     passwordField_1.setBounds(284, 265, 250, 28);
	    passwordField_1.setPlaceholder(" Password");
	    lblda.add(passwordField_1);
	    
	   
	      
	 

	    MyButton btnLogin = new MyButton();
	    btnLogin.setText("Login");
        btnLogin.setRadius(23);
        btnLogin.setBorderPainted(false);
	    btnLogin.setBackground(Color.white);
	    btnLogin.setForeground(Color.black);
	    
	   btnLogin.setBounds(310, 360, 200, 30); 
	    btnLogin.setFocusPainted(false);
	    lblda.add(btnLogin);

	    

	    JCheckBox showpass = new JCheckBox("Show password");
	      
	      
	      showpass.setFont(new Font("Sitka Small", Font.PLAIN, 13));
	      
	      showpass.setOpaque(false);
	      showpass.setBorderPainted(false);
	      showpass.setFocusPainted(false);
              showpass.setForeground(Color.white);
	      showpass.setBounds(350, 320, 120, 21);
	      lblda.add(showpass);
	  
	
	      
	      
	   
	      
	     
	      
	      
	     
	      
	      
	    
	      
	      
	      showpass.addActionListener(new ActionListener() {
	          public void actionPerformed(ActionEvent e) {
	              if(showpass.isSelected()) {
	               (passwordField_1).setEchoChar((char)0);
	              } else {
	               passwordField_1.setEchoChar('•');
	              }
	          }
	      });
	      
	      
	    
 
	      
	     btnLogin.addActionListener(new ActionListener() {
    public void actionPerformed(ActionEvent e) {
        String username = textField_1.getText();
        String password = new String(passwordField_1.getText());
        
        
        if (AuthenticationHandler.authenticateAdmin(username, password)==true) {
                    accessAdmin adminPanel = new accessAdmin();
                    passwordField_1.setText(null);
                    textField_1.setText(null);
            FlatAnimatedLafChange.showSnapshot();

                frame.getContentPane().remove(panel_1);
                frame.getContentPane().add(adminPanel);
            

            
            frame.revalidate();
            frame.repaint();
            FlatAnimatedLafChange.hideSnapshotWithAnimation();  
        } 
        
       else if(AuthenticationHandler.authenticateUser(username, password)==true){
            accessEm employePanel =new accessEm();
            passwordField_1.setText(null);
                    textField_1.setText(null);
                    FlatAnimatedLafChange.showSnapshot();

                frame.getContentPane().remove(panel_1);
                frame.getContentPane().add(employePanel);
            

            
            frame.revalidate();
            frame.repaint();
            FlatAnimatedLafChange.hideSnapshotWithAnimation();  
            
        } 
        

        
        
        else {
           
            JOptionPane.showMessageDialog(null, "Invalid Login Details", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
    }
});



	      
	     
	      
	      
	      btnLogin.addMouseListener(new MouseAdapter() {
	    	  
	    	  @Override
	    	  
	    	  public void mouseEntered(MouseEvent e) {
	    		  btnLogin.setBackground(new Color(155,176,193));
	    	  }
	    	  
	    	 
	    	  
	    	  
	    	  @Override
	    	  
	    	  public void mouseExited(MouseEvent e) {
	    		 // btnLogin.setBackground(Color.GRAY);
	    	  }
	    	   
	      });
	      
              
              

 	   
	      
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
