/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admingui;

import raven.toast.Notifications;

import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.util.Date;

/**
 *
 * @author imoun
 */
public class Tick extends javax.swing.JPanel {
    private static final String url =
            "jdbc:sqlite:" + System.getProperty("user.dir") + "/parc.db";

          private DefaultComboBoxModel<String> gamesModel;
    /**
     * Creates new form Tick
     */
    public Tick() {
        initComponents();
         
        jTextField2.setEditable(false);
        getid();
        jComboBox2.setVisible(false);
         gamesModel = new DefaultComboBoxModel<>();
        populateGamesComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crazyPanel1 = new admingui.CrazyPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        crazyPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Selling Ticket:");
        crazyPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 260, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("ID:");
        crazyPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 70, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Number of Tickets:");
        crazyPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 160, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Ticket Type:");
        crazyPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 110, 20));

        jTextField2.setForeground(new java.awt.Color(102, 102, 102));
        jTextField2.setText("Enter ID");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        crazyPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 290, 30));

        jTextField3.setForeground(new java.awt.Color(102, 102, 102));
        jTextField3.setText("Enter Tickets");
        jTextField3.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTextField3ComponentAdded(evt);
            }
        });
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        crazyPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 120, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Selling Date:");
        crazyPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 140, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visitor", "Player" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        crazyPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 120, -1));
        crazyPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 160, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Total:");
        crazyPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 80, 20));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("VALIDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        crazyPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, -1, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        crazyPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 180, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ticket (4).png"))); // NOI18N
        crazyPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        crazyPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 120, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        if(jTextField2.getText().equals("Enter ID")){
            jTextField2.setText("");
            jTextField2.setForeground(Color.black);        }
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        if(jTextField2.getText().equals("")){
            jTextField2.setText("Enter ID");
            jTextField2.setForeground(new Color(102,102,102));        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        if(jTextField3.getText().equals("Enter Tickets")){
            jTextField3.setText("");
            jTextField3.setForeground(Color.black);        }
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        if(jTextField3.getText().equals("")){
            jTextField3.setText("Enter Tickets");
            jTextField3.setForeground(new Color(102,102,102));        }
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
       
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
 if (jComboBox1.getSelectedItem().toString().equals("Player")) {


            jComboBox2.setVisible(true);

        } else {
         jComboBox2.setVisible(false);
        String n=jTextField3.getText();
        int numOfTickets = Integer.parseInt(n);
        numOfTickets =numOfTickets*100;

         jLabel7.setText(String.valueOf(numOfTickets)+" DA");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String id = jTextField2.getText();
    String numOfTickets = jTextField3.getText();
    int n= Integer.parseInt(numOfTickets);
    int prixv=n*100;
    String ticketType = jComboBox1.getSelectedItem().toString();
    Date sellingDate = jDateChooser1.getDate();
    String game= jComboBox2.getSelectedItem().toString();
    if(ticketType.equals("Visitor")){



    try (Connection conn = DriverManager.getConnection(url)) {
        String sql = "INSERT INTO ticket (IdTick, PrixTick, `Date_Achat_Tick`, Game) VALUES (?, ?, ?,?)";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1, id);
        stmt.setString(2, String.valueOf(prixv));
        stmt.setDate(3, new java.sql.Date(sellingDate.getTime()));
        stmt.setString(4,ticketType);

        int rowsAffected = stmt.executeUpdate();
        if (rowsAffected > 0) {
            Notifications.getInstance().show(Notifications.Type.INFO, Notifications.Location.TOP_CENTER, "Purshased");
            jTextField2.setText("Enter ID");
            jTextField3.setText("Enter Tickets");
            jLabel7.setText("");
        } else {


        }
    } catch (SQLException ex) {
        ex.printStackTrace();

    }

}
else if(ticketType.equals("Player")) {
         String gamet= jComboBox2.getSelectedItem().toString();
    String[] parts = gamet.split(" "); // Split the game name from the price
    String gameName = parts[0];
        double price = Double.parseDouble(game.split(" ")[1].split("-")[0]);
        double d=price*n;
        try (Connection conn = DriverManager.getConnection(url)) {
            String sql = "INSERT INTO ticket (IdTick, PrixTick, `Date_Achat_Tick`, Game) VALUES (?, ?, ?,?)";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, id);
            stmt.setDouble(2, price);
            stmt.setDate(3, new java.sql.Date(sellingDate.getTime()));
            stmt.setString(4, gameName);

            int rowsAffected = stmt.executeUpdate();
            if (rowsAffected > 0) {
                Notifications.getInstance().show(Notifications.Type.INFO, Notifications.Location.TOP_CENTER, "Success");
                 jTextField2.setText("Enter ID");
            jTextField3.setText("Enter Tickets");
                jLabel7.setText("");
            } else {
                // Handle failure to insert
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
}


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
  String selectedGame = jComboBox2.getSelectedItem().toString();


    if (selectedGame.matches(".+\\s\\d+\\.\\d+-DA")) {
        double price = Double.parseDouble(selectedGame.split(" ")[1].split("-")[0]);


        try {
            int numOfTickets = Integer.parseInt(jTextField3.getText());
            double totalPrice = price * numOfTickets;
            jLabel7.setText( totalPrice + " DA");
        } catch (NumberFormatException e) {

            jLabel7.setText("Invalid number of tickets");
        }
    } else {

        jLabel7.setText("");
    }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField3ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTextField3ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ComponentAdded

    
    public void showForm(JPanel component) {
    
    removeAll();

   
    setLayout(new FlowLayout());

    
    add(component);

    
    repaint();
    revalidate();

    
   }
  
         private void populateGamesComboBox() {
             String sql = "SELECT NomAtt, Cout FROM attraction";
    try {
        java.sql.Connection conn = DriverManager.getConnection(url);
        PreparedStatement stmt = conn.prepareStatement(sql);
        ResultSet tt = stmt.executeQuery();

        gamesModel.removeAllElements(); 

        while (tt.next()) {
            String gameName = tt.getString("NomAtt");
            double price = tt.getDouble("Cout");
            String item =   gameName +" " + price + "-DA";
            gamesModel.addElement(item); 
        }

        jComboBox2.setModel(gamesModel); 

        tt.close();
        stmt.close();
        conn.close();
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    }
    
          private void getid(){
          String sql = "SELECT MAX(IdTick) + 1 AS NextId FROM ticket";
try (Connection conn = DriverManager.getConnection(url);
     PreparedStatement stmt = conn.prepareStatement(sql)) {        

    ResultSet tt = stmt.executeQuery();
    if (tt.next()) {
        int nextId = tt.getInt("NextId");
        
        jTextField2.setText(String.valueOf(nextId));
    } else {
        
        jTextField2.setText("1"); 
    }
} catch (SQLException e) {
   
    e.printStackTrace();
}
        
 }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private admingui.CrazyPanel crazyPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
